test

diff --git a/.github/workflows/reuse-deployment.yml b/.github/workflows/reuse-deployment.yml
--- a/.github/workflows/reuse-deployment.yml
+++ b/.github/workflows/reuse-deployment.yml
@@ -53,11 +53,6 @@ jobs:
         with:
            version: 'latest'  
            
-      - name: Test AWS secrets
-        run: |
-          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
-          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"     
-
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
@@ -114,16 +109,22 @@ jobs:
         run: |
            kubectl apply -f ${{ inputs.k8s-manifest-dir }}
 
-      - name: Wait for Ingress External IP
+      - name: Wait for Service LoadBalancer Hostname
+        id: set-ingress-host 
         run: |
-          echo "Waiting for Ingress External IP..."
-          kubectl -n ${{ inputs.namespace }} wait --for=condition=ready ingress/solar-system --timeout=180s
-          EXTERNAL_IP=$(kubectl -n ${{ inputs.namespace }} get ingress solar-system -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
-          echo "APP_INGRESS_HOST=$EXTERNAL_IP" >> $GITHUB_OUTPUT
+           echo "Waiting for External Hostname..." EXTERNAL_HOST="" for i in {1..30}; do
+           EXTERNAL_HOST=$(kubectl -n ${{ inputs.namespace }} get svc solar-system -o jsonpath='{.status.loadBalancer.ingress[0].hostname}') if [ ! -z "$EXTERNAL_HOST" ]; then
+           if [ ! -z "$EXTERNAL_HOST" ]; then 
+           break 
+           fi 
+           echo "Waiting 10s..." 
+           sleep 10 
+           done
+           if [ -z "$EXTERNAL_HOST" ]; then 
+           echo "ERROR: External hostname not assigned" 
+           exit 1 
+           fi 
+           echo "APP_INGRESS_HOST=$EXTERNAL_HOST" >> $GITHUB_OUTPUT
 
-      - name: Output App URL
-        run: |
-          echo "Application URL: https://${{ steps.ingress-ip.outputs.APP_INGRESS_HOST }}"
-   
-    
-
+      - name: Output Application URL  
+        run: | echo "Application URL: https://${{ steps.set-ingress-host.outputs.APP_INGRESS_HOST }}"   
